pages:
  image:
    name: frankhjung/docbook:latest
    entrypoint: [""]
  stage: deploy
  script:
    - rm -rf public/
    - jw -f docbook -b html -o public index.sgml
  artifacts:
    paths:
      - public
  except:
    - tags
  only:
    - master

